# src/main/resources/application.yml

server:
  port: 8080

spring:
  application:
    name: DevOpsGPT
  # ======================================================
  #      SPRING AI CONFIGURATION FOR OPENAI
  # ======================================================
  ai:
    openai:
      api-key: ${OPENAI_API_KEY} # Load from environment variables
      chat:
        options:
          # Specify the model you want to use. 'gpt-4o' is a great, recent choice.
          model: omni-moderation-latest
          temperature: 0.7 # Controls the creativity of the model

springdoc:
  swagger-ui:
    # Controls the expansion depth of the schemas. -1 collapses all.
    default-models-expand-depth: -1
    # Path for the Swagger UI endpoint
    path: /swagger-ui.html
  api-docs:
    # Path for the generated OpenAPI specification
    path: /v3/api-docs
  # General API metadata
  info:
    title: DevOpsGPT API
    description: "API for the DevOps & Cloud AI Assistant. Provides endpoints for intelligent chat and command generation."
    version: "1.0.0"
    contact:
      name: DevOpsGPT Team
      email: api-support@devopsgpt.com
    license:
      name: Apache 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0.html